# CLEAR TABLES
# ...

# CREATE TABLES
CREATE TABLE user(
  id BINARY(16) NOT NULL,
  name VARCHAR(40) NOT NULL DEFAULT '',
  secret BINARY(16) NOT NULL DEFAULT UNHEX(REPLACE(UUID(), '-', '')),
  

  PRIMARY KEY (id)
);

CREATE TABLE bot(
  id INT NOT NULL AUTO_INCREMENT,
  

  PRIMARY KEY (id)
);

CREATE TABLE hook(
  id INT NOT NULL AUTO_INCREMENT,
  
  name VARCHAR(126) NOT NULL DEFAULT '',
  channel_id VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NOT NULL,
  guild_id VARCHAR(255) NOT NULL,
  hook_id VARCHAR(255) NOT NULL,

  link VARCHAR(255) NOT NULL DEFAULT '',

  PRIMARY KEY (id)
);



# INITIALIZE DEFAULT DATA
# ...

